server:
  port: 10004
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://192.168.2.150:10000/eureka
spring:
  application:
    name: ManagerConsumer
  freemarker:
    suffix: .ftl
    template-loader-path:
    - classpath:/templates/