server:
  port: 10003
spring:
  application:
    name: ActivitiProvider
  datasource:
    name: druid-datasource
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.150:3306/atcrowdfunding180725?serverTimezone=UTC&useSSL=true&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8

eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.150:10000/eureka